### ISSUE TITLE
use pysoundfile for wave io

### ISSUE THREAD

**Issue by Nitnelav** [Universite-Gustave-Eiffel/acoustic-toolbox#17]

**Comment by Nitnelav** [comment]
Mmmmm not sure it is such a good idea after all, the project does not seem stable at all, way less than scipy.io at least

**Comment by Nitnelav** [comment]
also scipy.io was updated a few years ago (https://docs.scipy.org/doc/scipy/release/1.6.0-notes.html#scipy-io-improvements) to read 24bit WAV files, which was the main argument for switching to pysoundfile

**Comment by MitchellAcoustics** [comment]
For what it's worth, Soundscapy subclasses the `Signal` class and uses it to work with 24bit and 32bit floating point WAVs and I've never had an issue.
